### ISSUE TITLE
discord vote system doesnt work

### ISSUE THREAD

**Issue by cattoman1** [extraes/BW-Chaos#4] opened 2022-05-08 22:42 UTC
so i did everything like it was in the yt vids and discription but it gives me this error:
 00:38:10.882] [BWChaos] Connected to the bot!
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'DSharpPlus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null'
   at BWChaosRemoteVoting.DiscordBot.Init(String token, UInt64 channelId)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BWChaosRemoteVoting.DiscordBot.Init(String token, UInt64 channelId)
   at BWChaosRemoteVoting.Program.MainAsync()
   at BWChaosRemoteVoting.Program.Main()

[00:38:11.200] [BWChaos] [ERROR] An error has occured within the remote voting process!
[00:38:11.201] [BWChaos] [ERROR] System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'DSharpPlus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null'
   at BWChaosRemoteVoting.DiscordBot.Init(String token, UInt64 channelId)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BWChaosRemoteVoting.DiscordBot.Init(String token, UInt64 channelId)
   at BWChaosRemoteVoting.Program.MainAsync()
   at BWChaosRemoteVoting.Program.Main()

[00:38:13.257] [BWChaos] Disconnected from the voting process. If you didn't close the game, make sure your antivirus isn't killing it

**Comment by gobboo** [comment] 2022-05-13 13:40
I get the same issue, going to try build it myself and see if I can get the dependency fixed :)

**Comment by extraes** [comment] 2022-05-15 04:14
fixed in 2.2.2 - inability to find DSharpPlus was caused by enabling ReadyToRun compilation, then another error was hit as a result of Discord changing things in their API, which was fixed in Chaos by updating the version of DSharpPlus used.

**Closed as completed by extraes** 2022-05-15 04:14 UTC
